services:
  mosquitto:
    build:
      context: .
      dockerfile: docker/mosquitto/Dockerfile
    container_name: mosquitto
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./certs:/mosquitto/certs:rw
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:rw
      - ./log:/mosquitto/log:rw
    ports:
      - "8883:8883"
    networks:
      - mqtt_network
    environment:
      - TZ=America/Sao_Paulo

    
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: mosquitto_api
    restart: unless-stopped
    volumes:
      - ./certs:/app/certs:rw
      - ./config:/app/config:rw
      - ./log:/app/log:rw
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - mqtt_network
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    depends_on:
      - mosquitto


networks:
  mqtt_network:
    driver: bridge

